import { useEffect, useState } from 'react'
import { Menu, X } from 'lucide-react'
import Button from './Button'; import Container from './Container'
const links = [{ name: 'Home', path: '/' }, { name: 'Courses', path: '/courses' }, { name: 'Gallery', path: '/gallery' }, { name: 'About', path: '/about' }, { name: 'Contact', path: '/contact' }]
const navigate = path => { window.history.pushState({}, '', path); window.dispatchEvent(new Event('app:navigate')); window.scrollTo({ top: 0, behavior: 'smooth' }) }
export default function Navbar() { const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const [path, setPath] = useState(window.location.pathname)
  useEffect(() => { const scroll = () => setScrolled(window.scrollY > 28); const update = () => setPath(window.location.pathname); window.addEventListener('scroll', scroll); window.addEventListener('popstate', update); window.addEventListener('app:navigate', update); return () => { window.removeEventListener('scroll', scroll); window.removeEventListener('popstate', update); window.removeEventListener('app:navigate', update) } }, [])
  const go = to => { setOpen(false); navigate(to) }
  return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled ? 'bg-ink/95 py-3 shadow-lg backdrop-blur-xl' : 'bg-ink/30 py-5 backdrop-blur-sm'}`}><Container className="flex items-center justify-between"><button onClick={() => go('/')} className="flex items-center gap-3 text-left"><img src="/images/aathichoodi-logo.jpg" className="h-10 w-10 rounded-full object-cover ring-2 ring-gold"/><span className="font-display text-lg font-bold text-white">Aathichoodi <i className="font-normal text-gold">Academy</i></span></button><div className="hidden items-center gap-7 md:flex">{links.map(x => <button key={x.path} onClick={() => go(x.path)} className={`text-sm font-medium transition ${path === x.path ? 'text-gold' : 'text-white/75 hover:text-gold'}`}>{x.name}</button>)}<Button href="/contact" onClick={e => { e.preventDefault(); go('/contact') }}>Enroll now</Button></div><button onClick={() => setOpen(!open)} className="text-white md:hidden">{open ? <X/> : <Menu/>}</button>{open && <div className="absolute left-4 right-4 top-16 flex flex-col gap-4 rounded-2xl bg-navy p-5 shadow-premium md:hidden">{links.map(x => <button key={x.path} onClick={() => go(x.path)} className={`text-left ${path === x.path ? 'text-gold' : 'text-white/80'}`}>{x.name}</button>)}<Button href="/contact" onClick={e => { e.preventDefault(); go('/contact') }}>Enroll now</Button></div>}</Container></header> }
